
export const posts = [
  {
    id: "1",
    user: "user_1234",
    time: "1h ago",
    image: "../images/post1.png",
    text: "Anyone want to rate me or not?",
    likes: 70,
    comments: [
      { user: "user_5678", text: "Looking great! 🔥" },
      { user: "user_9876", text: "Nice one! 👍" },
    ],
  },
  {
    id: "2",
    user: "user_1234",
    time: "1h ago",
    image: "https://source.unsplash.com/random/301x201",
    text: "This is you love, anyone online here to chat?",
    likes: 50,
    comments: [{ user: "user_4321", text: "Hello! 😊" }],
  },
  {
    id: "3",
    user: "user_1234",
    time: "1h ago",
    image: "https://source.unsplash.com/random/301x201",
    text: "This is you love, anyone online here to chat?",
    likes: 50,
    comments: [],
  },
  {
    id: "4",
    user: "user_1234",
    time: "1h ago",
    image: "https://source.unsplash.com/random/301x201",
    text: "This is you love, anyone online here to chat?",
    likes: 50,
    comments: [],
  },{
    id: "5",
    user: "user_1234",
    time: "1h ago",
    image: "https://source.unsplash.com/random/301x201",
    text: "This is you love, anyone online here to chat?",
    likes: 50,
    comments: [],
  },{
    id: "6",
    user: "user_1234",
    time: "1h ago",
    image: "https://source.unsplash.com/random/301x201",
    text: "This is you love, anyone online here to chat?",
    likes: 50,
    comments: [],
  },
  {
    id: "7",
    user: "user_1234",
    time: "1h ago",
    image: "https://source.unsplash.com/random/301x201",
    text: "This is you love, anyone online here to chat?",
    likes: 50,
    comments: [],
  },
];
